name: scrolling_subtitles
description: Lets you view subtitles of a video in scrolling format.
publish_to: "none"

version: 1.3.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  subtitle: ^0.1.0-beta.3
  blur: ^3.1.0
  file_picker: ^6.0.0
  provider: ^6.0.5
  dart_casing: ^3.0.1
  gradient_borders: ^1.0.0
  window_manager: ^0.3.6
  flex_color_picker: ^3.3.0
  gap: ^3.0.1
  shared_preferences: ^2.2.2
  media_kit: ^1.1.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
